spring:
  application:
    name: ruyuan-eshop-order
  shardingsphere:
    props:
      sql:
        show: false
    # 数据源配置
    datasource:
      names: ds0,ds1,ds2,ds3,ds4,ds5,ds6,ds7
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ruyuan_eshop_order_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        min-idle: 1
        initial-size: 1
        max-active: 5
        max-wait: 6000
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ruyuan_eshop_order_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        min-idle: 1
        initial-size: 1
        max-active: 5
        max-wait: 6000
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ruyuan_eshop_order_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        min-idle: 1
        initial-size: 1
        max-active: 5
        max-wait: 6000
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ruyuan_eshop_order_3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        min-idle: 1
        initial-size: 1
        max-active: 5
        max-wait: 6000
      ds4:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ruyuan_eshop_order_4?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        min-idle: 1
        initial-size: 1
        max-active: 5
        max-wait: 6000
      ds5:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ruyuan_eshop_order_5?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        min-idle: 1
        initial-size: 1
        max-active: 5
        max-wait: 6000
      ds6:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ruyuan_eshop_order_6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        min-idle: 1
        initial-size: 1
        max-active: 5
        max-wait: 6000
      ds7:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ruyuan_eshop_order_7?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        min-idle: 1
        initial-size: 1
        max-active: 5
        max-wait: 6000
    # 分片配置
    sharding:
      # 默认的数据源  order_auto_no、order_cancel_scheduled_task、undo_log等三个表不做分库分库，都会走默认的数据源
      default-data-source-name: ds0
      # 默认的分库策略
      default-database-strategy:
        standard:
          sharding-column: order_id
          precise-algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomDatabasePreciseShardingAlgorithm
      # 分表配置
      tables:
        # 只需要分库的表配置
        ruyuan_tend_consistency_task:
          actual-data-nodes: ds$->{0..7}.ruyuan_tend_consistency_task
          database-strategy:
            inline:
              sharding-column: shard_key
              algorithm-expression: ds$->{shard_key % 8}
        # 正向订单业务表
        order_info:
          actual-data-nodes: ds$->{0..7}.order_info_$->{0..63}
          database-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomDatabaseComplexKeysShardingAlgorithm
          table-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTableComplexKeysShardingAlgorithm
        order_item:
          actual-data-nodes: ds$->{0..7}.order_item_$->{0..63}
          database-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomDatabaseComplexKeysShardingAlgorithm
          table-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTableComplexKeysShardingAlgorithm
        order_payment_detail:
          actual-data-nodes: ds$->{0..7}.order_payment_detail_$->{0..63}
          database-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomDatabaseComplexKeysShardingAlgorithm
          table-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTableComplexKeysShardingAlgorithm
        order_amount:
          actual-data-nodes: ds$->{0..7}.order_amount_$->{0..63}
          table-strategy:
            standard:
              sharding-column: order_id
              precise-algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTablePreciseShardingAlgorithm
        order_amount_detail:
          actual-data-nodes: ds$->{0..7}.order_amount_detail_$->{0..63}
          table-strategy:
            standard:
              sharding-column: order_id
              precise-algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTablePreciseShardingAlgorithm
        order_delivery_detail:
          actual-data-nodes: ds$->{0..7}.order_delivery_detail_$->{0..63}
          database-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomDatabaseComplexKeysShardingAlgorithm
          table-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTableComplexKeysShardingAlgorithm
        order_operate_log:
          actual-data-nodes: ds$->{0..7}.order_operate_log_$->{0..63}
          table-strategy:
            standard:
              sharding-column: order_id
              precise-algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTablePreciseShardingAlgorithm
        order_snapshot:
          actual-data-nodes: ds$->{0..7}.order_snapshot_$->{0..63}
          table-strategy:
            standard:
              sharding-column: order_id
              precise-algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTablePreciseShardingAlgorithm
        # 逆向售后业务表
        after_sale_info:
          actual-data-nodes: ds$->{0..7}.after_sale_info_$->{0..63}
          database-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomDatabaseComplexKeysShardingAlgorithm
          table-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTableComplexKeysShardingAlgorithm
        after_sale_item:
          actual-data-nodes: ds$->{0..7}.after_sale_item_$->{0..63}
          database-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomDatabaseComplexKeysShardingAlgorithm
          table-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTableComplexKeysShardingAlgorithm
        after_sale_log:
          actual-data-nodes: ds$->{0..7}.after_sale_log_$->{0..63}
          table-strategy:
            standard:
              sharding-column: after_sale_id
              precise-algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTablePreciseShardingAlgorithm
        after_sale_refund:
          actual-data-nodes: ds$->{0..7}.after_sale_refund_$->{0..63}
          database-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomDatabaseComplexKeysShardingAlgorithm
          table-strategy:
            complex:
              sharding-columns: order_id,user_id,after_sale_id,parent_order_id
              algorithm-class-name: com.ruyuan.eshop.order.config.sharding.CustomTableComplexKeysShardingAlgorithm
      # 绑定表配置
      binding-tables:
        - order_info,order_item,order_payment_detail,order_delivery_detail
        - after_sale_info,after_sale_item,after_sale_refund

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 18005
      # 使用nacos做持久化
      datasource:
        # 微服务流控配置
        flow:
          nacos:
            server-addr: localhost:8848
            namespace: sentinel
            group-id: SENTINEL_GROUP
            data-id: ${spring.application.name}-flow-rules.json
            data-type: json
            rule-type: flow
        # 熔断降级配置
        degrade:
          nacos:
            server-addr: localhost:8848
            namespace: sentinel
            group-id: SENTINEL_GROUP
            data-id: ${spring.application.name}-degrade-rules.json
            data-type: json
            rule-type: degrade
        # 热点规则
        param-flow:
          nacos:
            server-addr: localhost:8848
            namespace: sentinel
            group-id: SENTINEL_GROUP
            data-id: ${spring.application.name}-param-flow-rules.json
            data-type: json
            rule-type: param-flow
        # 系统规则
        system:
          nacos:
            server-addr: localhost:8848
            namespace: sentinel
            group-id: SENTINEL_GROUP
            data-id: ${spring.application.name}-system-rules.json
            data-type: json
            rule-type: system
        # 授权规则
        authority:
          nacos:
            server-addr: localhost:8848
            namespace: sentinel
            group-id: SENTINEL_GROUP
            data-id: ${spring.application.name}-authority-rules.json
            data-type: json
            rule-type: authority

  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000
    database: 0

  data:
    mongodb:
      database: order_operate_log
      uri: mongodb://order:order@192.168.0.222:27017,192.168.0.222:27018,192.168.0.222:27019/order_operate_log?slaveOk=true&write=1&readPreference=secondaryPreferred&connectTimeoutMS=30000&replicaSet=ruyuan_rs

server:
  port: 8005

dubbo:
  scan:
    base-packages: com.ruyuan.eshop.order.api
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28085
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
  cloud:
    subscribed-services: ruyuan-eshop-order,ruyuan-eshop-product,ruyuan-eshop-market,ruyuan-eshop-inventory,ruyuan-eshop-pay,ruyuan-eshop-customer,ruyuan-eshop-risk,ruyuan-eshop-address,ruyuan-eshop-fulfill,ruyuan-eshop-wms,ruyuan-eshop-tms

mybatis-plus:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


rocketmq:
  name-server: localhost:9876

#xxl-job配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: ruyuan-order-service

ruyuan:
  tend:
    consistency:
      parallel:
        pool:
          # 不配置默认值就是5
          thread-max-pool-size: 5
          # 不配置默认值就是5
          thread-core-pool-size: 5
          # 不配置默认值就是60
          thread-pool-keep-alive-time: 60
          # 不配置默认值就是SECONDS
          thread-pool-keep-alive-time-unit: SECONDS
          # 不配置默认值就是100
          thread-pool-queue-size: 100
      action:
        # 默认值是0 也就是 只要出现失败的情况，就会走降级逻辑，这里记的配置降级类。如果没有配置降级类，则不会走降级逻辑
        fail-count-threshold: 0
      shard:
        # 表示任务表一个库中，如果确认使用单库模式，可以不配置 默认就是false  这里只是为了说明，就写了出来
        task-sharded: false

# elasticsearch相关配置信息
elasticsearch:
  # 集群节点，多个节点采用逗号分隔，需要替换为ecs的ip
  clusterNodes: localhost:9200
  shards-number: 3
  replicas-number: 2
  return-size: 10000
  search-result-size: 20

management:
  health:
    db:
      enabled: false

hbase:
  config:
    hbase:
      zookeeper:
        quorum: 172.19.16.48:2181
      client:
        username: root
        password: hbase123!@#

canal:
  binlog:
    consumer:
      enable: true