################################################## mybatis-plus 配置 ##################################################
mybatis-plus.global-config.banner: false
mybatis-plus.global-config.db-config.id-type: auto
mybatis-plus.global-config.db-config.logic-delete-value: 1 # 逻辑已删除值(默认为 1)
mybatis-plus.global-config.db-config.logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
mybatis-plus.configuration.map-underscore-to-camel-case: true # 关闭驼峰写法
mybatis-plus.mapper-locations: classpath:mapper/*.xml
################################################## mybatis-plus 配置 ##################################################

################################################## MySQL 配置 ##################################################
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
# spring.datasource.url: jdbc:mysql://${MYSQL_URL}/ahaodb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false&rewriteBatchedStatements=true&useAffectedRows=true
# spring.datasource.username: root
# spring.datasource.password: root

spring.datasource.hikari.minimum-idle: 10           # 最小空闲连接数 保持和最大连接数一致，避免空闲超时
spring.datasource.hikari.maximum-pool-size: 30      # 最大连接数
spring.datasource.hikari.connectionTimeout: 60000   # 连接建立超时时间 单位ms 默认30000
spring.datasource.hikari.idleTimeout: 600000        # 空闲连接超时时间 单位ms 最小10000(10s) 默认600000(10min)
spring.datasource.hikari.connection-test-query: SELECT 1
################################################## MySQL 配置 ##################################################
