# =================================== sentinel 配置 ==========================================
spring.cloud.sentinel.transport.dashboard: 192.168.19.128:8080
spring.cloud.sentinel.transport.port: 18005

# 微服务流控配置
spring.cloud.sentinel.datasource.flow.nacos.server-addr: ${spring.cloud.nacos.server-addr}
spring.cloud.sentinel.datasource.flow.nacos.namespace: sentinel
spring.cloud.sentinel.datasource.flow.nacos.group-id: SENTINEL_GROUP
spring.cloud.sentinel.datasource.flow.nacos.data-id: ${spring.application.name}-flow-rules.json
spring.cloud.sentinel.datasource.flow.nacos.data-type: json
spring.cloud.sentinel.datasource.flow.nacos.rule-type: flow
# 熔断降级配置
spring.cloud.sentinel.datasource.degrade.nacos.server-addr: ${spring.cloud.nacos.server-addr}
spring.cloud.sentinel.datasource.degrade.nacos.namespace: sentinel
spring.cloud.sentinel.datasource.degrade.nacos.group-id: SENTINEL_GROUP
spring.cloud.sentinel.datasource.degrade.nacos.data-id: ${spring.application.name}-degrade-rules.json
spring.cloud.sentinel.datasource.degrade.nacos.data-type: json
spring.cloud.sentinel.datasource.degrade.nacos.rule-type: degrade
# 热点规则
spring.cloud.sentinel.datasource.param-flow.nacos.server-addr: ${spring.cloud.nacos.server-addr}
spring.cloud.sentinel.datasource.param-flow.nacos.namespace: sentinel
spring.cloud.sentinel.datasource.param-flow.nacos.group-id: SENTINEL_GROUP
spring.cloud.sentinel.datasource.param-flow.nacos.data-id: ${spring.application.name}-param-flow-rules.json
spring.cloud.sentinel.datasource.param-flow.nacos.data-type: json
spring.cloud.sentinel.datasource.param-flow.nacos.rule-type: param-flow
# 系统规则
spring.cloud.sentinel.datasource.system.nacos.server-addr: ${spring.cloud.nacos.server-addr}
spring.cloud.sentinel.datasource.system.nacos.namespace: sentinel
spring.cloud.sentinel.datasource.system.nacos.group-id: SENTINEL_GROUP
spring.cloud.sentinel.datasource.system.nacos.data-id: ${spring.application.name}-system-rules.json
spring.cloud.sentinel.datasource.system.nacos.data-type: json
spring.cloud.sentinel.datasource.system.nacos.rule-type: system
# 授权规则
spring.cloud.sentinel.datasource.authority.nacos.server-addr: ${spring.cloud.nacos.server-addr}
spring.cloud.sentinel.datasource.authority.nacos.namespace: sentinel
spring.cloud.sentinel.datasource.authority.nacos.group-id: SENTINEL_GROUP
spring.cloud.sentinel.datasource.authority.nacos.data-id: ${spring.application.name}-authority-rules.json
spring.cloud.sentinel.datasource.authority.nacos.data-type: json
spring.cloud.sentinel.datasource.authority.nacos.rule-type: authority
# =================================== sentinel 配置 ==========================================
