################################################## RocketMQ 配置 ##################################################
rocketmq.name-server: 192.168.19.128:9876
################################################## RocketMQ 配置 ##################################################
