server.port: 8008

spring.datasource.url: jdbc:mysql://192.168.19.128:3306/ahao_wms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false&rewriteBatchedStatements=true&useAffectedRows=true
spring.datasource.username: root
spring.datasource.password: root
