server.port: 8001

spring.datasource.url: jdbc:mysql://192.168.19.128:3306/ahao_inventory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false&rewriteBatchedStatements=true&useAffectedRows=true
spring.datasource.username: root
spring.datasource.password: root

#seata配置
seata:
  enable-auto-data-source-proxy: false # 如果引入的是seata-spring-boot-starter 请关闭自动代理，需要关闭自动代理
  application-id: seata-server # Seata应用的名称
  tx-service-group: default_tx_group # 事务组
  service:
    vgroup-mapping:
      default_tx_group: default
  config:
    type: nacos
    nacos:
      server-addr: 192.168.19.128:8848 # Nacos服务地址
#      namespace: # Seata的NameSpace ID
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos # 基于Nacos实现分布式事务管理
    nacos:
      server-addr: 192.168.19.128:8848 # Nacos服务地址
#      namespace: # Seata的NameSpace ID
      group: SEATA_GROUP
      username: nacos
      password: nacos
      cluster: default
      application: seata-server
